# Generated by Django 4.0 on 2022-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0031_sales_bill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='bill_status',
        ),
        migrations.AddField(
            model_name='dummytable',
            name='bill_status',
            field=models.BooleanField(default=False),
        ),
    ]
